package io.micronaut.datarest.postgrest;

import io.micronaut.datarest.core.Dialect;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.Network;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

import java.net.URI;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

public class PostgreSQL {
    private static final int POSTGREST_PORT = 3000;
    /** Set once the containers are up, so several test classes can share them. */
    private static String url;
    private static Throwable setupFailure;

    private static final Network NETWORK = Network.newNetwork();
    private static final String DB_ALIAS = "db";
    private static final String DB_NAME = "demo";
    private static final String DB_USER = "demo";
    private static final String DB_PASSWORD = "Demo_123";
    /** Role PostgREST switches to for unauthenticated requests; it is granted nothing. */
    private static final String ANON_ROLE = "web_anon";
    /** Role named in the JWT {@code role} claim; it owns the table privileges. */
    private static final String USER_ROLE = "web_user";
    /** HS256 secret PostgREST verifies tokens with; PostgREST requires at least 32 characters. */
    private static final String JWT_SECRET = "datarest-tck-secret-that-is-at-least-32-chars-long";

    private static final PostgreSQLContainer DB = new PostgreSQLContainer(DockerImageName.parse("postgres:18"))
        .withDatabaseName(DB_NAME)
        .withUsername(DB_USER)
        .withPassword(DB_PASSWORD)
        .withNetwork(NETWORK)
        .withNetworkAliases(DB_ALIAS);

    private static final GenericContainer<?> POSTGREST = new GenericContainer<>(
        DockerImageName.parse("postgrest/postgrest:v16.4"))
        .dependsOn(DB)
        .withNetwork(NETWORK)
        .withExposedPorts(POSTGREST_PORT)
        .waitingFor(Wait.forHttp("/").forPort(POSTGREST_PORT).forStatusCode(200)
            .withStartupTimeout(Duration.ofMinutes(2)));

    private static final List<String> SETUP_SQL = List.of(
        """
        create table books (
          id        bigint generated by default as identity primary key,
          title     varchar(200) not null,
          author    varchar(200),
          published date
        )""",
        "create function count_books() returns bigint language sql stable as $$ select count(*) from books $$",
        // PostgREST exposes whatever the request's role may see. The anonymous role gets nothing, so
        // unauthenticated requests fail; the role named in the JWT gets the table privileges.
        "create role " + ANON_ROLE + " nologin",
        "create role " + USER_ROLE + " nologin",
        "grant usage on schema public to " + USER_ROLE,
        "grant select, insert, update, delete on all tables in schema public to " + USER_ROLE,
        "grant usage, select on all sequences in schema public to " + USER_ROLE,
        "grant execute on function count_books() to " + USER_ROLE,
        "grant " + ANON_ROLE + " to " + DB_USER,
        "grant " + USER_ROLE + " to " + DB_USER);


    public static Map<String, String> getProperties() {
        return getProperties("default");
    }

    public static synchronized Map<String, String> getProperties(String nameQualifier) {
        if (setupFailure != null) {
            // Report the original failure to every test class instead of re-running a half-applied setup.
            throw new IllegalStateException("PostgREST fixture setup failed", setupFailure);
        }
        if (url == null) {
            try {
                DB.start();
                executeSQL();
                startRest();
                url = new URI("http", null, POSTGREST.getHost(), POSTGREST.getMappedPort(POSTGREST_PORT), null, null, null).toString();
            } catch (RuntimeException | URISyntaxException e) {
                setupFailure = e;
                throw new IllegalStateException("PostgREST fixture setup failed", e);
            }
        }
        return Map.of(
            "restdatasources." + nameQualifier + ".dialect", Dialect.POSTGREST.toString(),
            "restdatasources." + nameQualifier + ".url", url);
    }

    /**
     * @return the PostgREST base URL, once the containers are up
     */
    public static String getUrl() {
        getProperties();
        return url;
    }

    /**
     * @return an HS256 JWT whose {@code role} claim switches PostgREST to the privileged role
     */
    public static String bearerToken() {
        String header = base64Url("{\"alg\":\"HS256\",\"typ\":\"JWT\"}".getBytes(StandardCharsets.UTF_8));
        String payload = base64Url(("{\"role\":\"" + USER_ROLE + "\"}").getBytes(StandardCharsets.UTF_8));
        String signingInput = header + "." + payload;
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(JWT_SECRET.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
            return signingInput + "." + base64Url(mac.doFinal(signingInput.getBytes(StandardCharsets.UTF_8)));
        } catch (GeneralSecurityException e) {
            throw new IllegalStateException("Could not sign the PostgREST JWT", e);
        }
    }

    private static String base64Url(byte[] bytes) {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }

    private static void startRest() {
        POSTGREST.withEnv(Map.of(
            "PGRST_DB_URI", "postgres://" + DB_USER + ":" + DB_PASSWORD + "@" + DB_ALIAS + ":5432/" + DB_NAME,
            "PGRST_DB_SCHEMAS", "public",
            "PGRST_DB_ANON_ROLE", ANON_ROLE,
            "PGRST_JWT_SECRET", JWT_SECRET));
        POSTGREST.start();
    }

    private static void executeSQL() {
        try (Connection connection = DriverManager.getConnection(DB.getJdbcUrl(), DB_USER, DB_PASSWORD);
             Statement statement = connection.createStatement()) {
            for (String sql : SETUP_SQL) {
                statement.execute(sql);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Could not create the books table", e);
        }
    }

}
