pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.1.4'
}

rootProject.name = 'micronaut-datarest-parent'

include 'datarest-tck'
include 'datarest'
include 'datarest-postgresql'
include 'datarest-ords'
include 'datarest-bom'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    useStandardizedProjectNames = true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-sql")
    importMicronautCatalog("micronaut-data")
    importMicronautCatalog("micronaut-reactor")
}
