package io.micronaut.datarest.postgresql;

import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.Network;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.util.List;
import java.util.Map;

public class PostgreSQL {
    private static final int POSTGREST_PORT = 3000;
    /** Set once the containers are up, so several test classes can share them. */
    private static String url;

    private static final Network NETWORK = Network.newNetwork();
    private static final String DB_ALIAS = "db";
    private static final String DB_NAME = "demo";
    private static final String DB_USER = "demo";
    private static final String DB_PASSWORD = "Demo_123";
    /** Role PostgREST switches to for unauthenticated requests. */
    private static final String ANON_ROLE = "web_anon";

    private static final PostgreSQLContainer DB = new PostgreSQLContainer(DockerImageName.parse("postgres:18"))
        .withDatabaseName(DB_NAME)
        .withUsername(DB_USER)
        .withPassword(DB_PASSWORD)
        .withNetwork(NETWORK)
        .withNetworkAliases(DB_ALIAS);

    private static final GenericContainer<?> POSTGREST = new GenericContainer<>(
        DockerImageName.parse("postgrest/postgrest:v16.4"))
        .dependsOn(DB)
        .withNetwork(NETWORK)
        .withExposedPorts(POSTGREST_PORT)
        .waitingFor(Wait.forHttp("/").forPort(POSTGREST_PORT).forStatusCode(200)
            .withStartupTimeout(Duration.ofMinutes(2)));

    private static final List<String> SETUP_SQL = List.of(
        """
        create table books (
          id        bigint generated by default as identity primary key,
          title     varchar(200) not null,
          author    varchar(200),
          published date
        )""",
        "create function count_books() returns bigint language sql stable as $$ select count(*) from books $$",
        // PostgREST exposes whatever the anonymous role may see; grants are the equivalent of ords.enable_object.
        "create role " + ANON_ROLE + " nologin",
        "grant usage on schema public to " + ANON_ROLE,
        "grant select, insert, update, delete on all tables in schema public to " + ANON_ROLE,
        "grant usage, select on all sequences in schema public to " + ANON_ROLE,
        "grant execute on function count_books() to " + ANON_ROLE,
        "grant " + ANON_ROLE + " to " + DB_USER);


    public static Map<String, String> getProperties() {
        return getProperties("default");
    }

    public static synchronized Map<String, String> getProperties(String nameQualifier) {
        if (url == null) {
            DB.start();
            executeSQL();
            startRest();
            try {
                url = new URI("http", null, POSTGREST.getHost(), POSTGREST.getMappedPort(POSTGREST_PORT), null, null, null).toString();
            } catch (URISyntaxException e) {
                throw new IllegalStateException("Could not create the PostegreSQL REST URL", e);
            }
        }
        return Map.of("restdatasources." + nameQualifier + ".url", url);
    }

    private static void startRest() {
        POSTGREST.withEnv(Map.of(
            "PGRST_DB_URI", "postgres://" + DB_USER + ":" + DB_PASSWORD + "@" + DB_ALIAS + ":5432/" + DB_NAME,
            "PGRST_DB_SCHEMAS", "public",
            "PGRST_DB_ANON_ROLE", ANON_ROLE));
        POSTGREST.start();
    }

    private static void executeSQL() {
        try (Connection connection = DriverManager.getConnection(DB.getJdbcUrl(), DB_USER, DB_PASSWORD);
             Statement statement = connection.createStatement()) {
            for (String sql : SETUP_SQL) {
                statement.execute(sql);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Could not create the books table", e);
        }
    }

}
